// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARazFmfqvUJs5onS6CFNXMqKypAkejCK0',
    appId: '1:830261947770:web:031ce746ac2e1c120bfac3',
    messagingSenderId: '830261947770',
    projectId: 'signin-example-41fa2',
    authDomain: 'signin-example-41fa2.firebaseapp.com',
    storageBucket: 'signin-example-41fa2.appspot.com',
    measurementId: 'G-3EK189VD83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeOfQJpQFcNUKqM_eKn5Vlnyr7Pp5raDs',
    appId: '1:830261947770:android:e74ac2a0b01240390bfac3',
    messagingSenderId: '830261947770',
    projectId: 'signin-example-41fa2',
    storageBucket: 'signin-example-41fa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdJRX1cx9KWOsVBzeXniairaV2-e3mh6g',
    appId: '1:830261947770:ios:ec9dd700238614260bfac3',
    messagingSenderId: '830261947770',
    projectId: 'signin-example-41fa2',
    storageBucket: 'signin-example-41fa2.appspot.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdJRX1cx9KWOsVBzeXniairaV2-e3mh6g',
    appId: '1:830261947770:ios:ec9dd700238614260bfac3',
    messagingSenderId: '830261947770',
    projectId: 'signin-example-41fa2',
    storageBucket: 'signin-example-41fa2.appspot.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARazFmfqvUJs5onS6CFNXMqKypAkejCK0',
    appId: '1:830261947770:web:ddf96c59f515dad00bfac3',
    messagingSenderId: '830261947770',
    projectId: 'signin-example-41fa2',
    authDomain: 'signin-example-41fa2.firebaseapp.com',
    storageBucket: 'signin-example-41fa2.appspot.com',
    measurementId: 'G-QJWVHVLLLK',
  );
}
